# Generated by Django 5.0.7 on 2025-12-16 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('networking', 'Networking'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('social', 'Social'), ('fundraiser', 'Fundraiser'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', max_length=20)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('attendee_count', models.IntegerField(default=0)),
                ('flyer_url', models.TextField(blank=True, db_column='flyer_url', null=True)),
                ('created_by', models.UUIDField(blank=True, db_column='created_by', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date', '-start_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField(db_column='image_url')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(db_column='display_order', default=0)),
            ],
            options={
                'db_table': 'event_images',
                'ordering': ['display_order', 'uploaded_at'],
                'managed': False,
            },
        ),
    ]
