-- Migration: Seed sample projects with comprehensive metadata
-- Date: 2025-10-23
-- Description: Insert sample projects with all required metadata fields

-- Insert sample projects with full metadata
INSERT INTO public.projects (
  title,
  description,
  objectives,
  deliverables,
  status,
  project_type,
  location,
  launch_date,
  timeline_start,
  timeline_end,
  image_url,
  tags,
  domain_tags,
  priority,
  max_participants,
  participants_count,
  human_skills_required,
  platform_requirements,
  devices_required,
  budget_estimate,
  current_budget,
  is_concurrent,
  created_at,
  updated_at
) VALUES
(
  'Mansa AI Research Initiative',
  'A groundbreaking research program focused on developing AI solutions tailored for African contexts, addressing local challenges in healthcare, agriculture, and education.',
  E'1. Develop culturally relevant AI models\n2. Build capacity in AI research across African institutions\n3. Create open-source AI tools for local problems\n4. Establish ethical AI guidelines for African contexts',
  E'• 3 AI models for local language processing\n• Open-source toolkit for African developers\n• Research papers on ethical AI in Africa\n• Training program for 50+ researchers',
  'Planning',
  'future',
  'Ghana, Nigeria, Kenya',
  '2025-06-01',
  '2025-06-01',
  '2026-05-31',
  '/cardimage1.png',
  '["AI", "Research", "Ethics", "Open Source"]'::jsonb,
  '["AI", "ML", "Research", "Ethics"]'::jsonb,
  'high',
  50,
  12,
  'Machine Learning Engineers, Data Scientists, Ethics Researchers, Software Developers, Technical Writers',
  'Python, TensorFlow, PyTorch, Cloud Computing (AWS/GCP), Jupyter Notebooks, Git, Docker',
  'High-performance GPUs, Cloud compute instances, Development workstations',
  150000.00,
  25000.00,
  true,
  NOW(),
  NOW()
),
(
  'CyberSecurity Training Platform',
  'Comprehensive cybersecurity training platform designed to build African cybersecurity capacity through hands-on labs, certifications, and real-world scenarios.',
  E'1. Increase cybersecurity awareness across Africa\n2. Provide accessible, affordable security training\n3. Create pathway to cybersecurity careers\n4. Develop Africa-specific security scenarios',
  E'• Interactive training platform with 100+ modules\n• Virtual labs for hands-on practice\n• Certification program recognized across Africa\n• 1000+ trained security professionals',
  'Concept',
  'future',
  'Pan-African (Online)',
  '2025-08-01',
  '2025-08-01',
  '2026-12-31',
  '/cardimage1.png',
  '["CyberSecurity", "Training", "Education", "Platform"]'::jsonb,
  '["CyberSecurity", "Education", "Cloud"]'::jsonb,
  'critical',
  1000,
  45,
  'Cybersecurity Experts, Platform Developers, UX/UI Designers, Content Creators, Instructors',
  'Web Development (React/Vue), Backend (Node.js/Django), Cloud Platform, LMS Integration, Video Streaming',
  'Web servers, Development environments, Video recording equipment, Cloud infrastructure',
  200000.00,
  15000.00,
  true,
  NOW(),
  NOW()
),
(
  'Digital Health Records System',
  'Blockchain-based digital health records system for secure, interoperable patient data management across African healthcare facilities.',
  E'1. Digitize patient health records across Africa\n2. Ensure data privacy and security\n3. Enable seamless data sharing between facilities\n4. Improve healthcare delivery efficiency',
  E'• Blockchain-based health records platform\n• Mobile app for patients and providers\n• Integration with 50+ healthcare facilities\n• HIPAA-compliant security framework',
  'Planning',
  'ongoing',
  'Ghana, South Africa',
  '2025-03-15',
  '2025-03-15',
  '2026-03-14',
  '/cardimage1.png',
  '["HealthTech", "Blockchain", "Security", "Mobile"]'::jsonb,
  '["BIOTECH", "Blockchain", "CyberSecurity"]'::jsonb,
  'high',
  30,
  18,
  'Blockchain Developers, Healthcare IT Specialists, Mobile App Developers, Security Engineers, Healthcare Professionals',
  'Blockchain (Ethereum/Hyperledger), Mobile (React Native), Backend (Python/Node.js), Cloud Infrastructure',
  'Blockchain nodes, Mobile devices for testing, Cloud servers, Development workstations',
  180000.00,
  45000.00,
  false,
  NOW(),
  NOW()
),
(
  'Agricultural AI Prediction System',
  'AI-powered platform for crop yield prediction, pest detection, and farming optimization using satellite imagery and local weather data.',
  E'1. Improve crop yields through AI predictions\n2. Early detection of plant diseases and pests\n3. Optimize resource allocation (water, fertilizer)\n4. Provide actionable insights to farmers',
  E'• Mobile app for 10,000+ farmers\n• AI models for 20+ crops\n• Weather integration and alerts\n• Pest detection with 90%+ accuracy',
  'Active',
  'ongoing',
  'Kenya, Tanzania, Uganda',
  '2024-11-01',
  '2024-11-01',
  '2025-10-31',
  '/cardimage1.png',
  '["Agriculture", "AI", "Satellite", "Mobile"]'::jsonb,
  '["AI", "ML", "IoT"]'::jsonb,
  'high',
  25,
  22,
  'Machine Learning Engineers, Agricultural Scientists, Mobile Developers, GIS Specialists, Data Analysts',
  'Python, TensorFlow, Satellite Imagery APIs, Mobile Development, GIS Tools, Weather APIs',
  'Smartphones, IoT sensors, Weather stations, Satellite data access, Cloud computing',
  120000.00,
  75000.00,
  true,
  NOW(),
  NOW()
),
(
  'Quantum Computing Research Lab',
  'Establish Africa\'s first quantum computing research laboratory to explore quantum algorithms and their applications in cryptography and optimization.',
  E'1. Build quantum computing expertise in Africa\n2. Research quantum algorithms for African problems\n3. Collaborate with international quantum institutes\n4. Train next generation of quantum researchers',
  E'• Quantum computing lab with access to quantum hardware\n• 5+ research papers on quantum applications\n• Training program for 30 researchers\n• Open-source quantum algorithm library',
  'Concept',
  'future',
  'South Africa',
  '2026-01-01',
  '2026-01-01',
  '2028-12-31',
  '/cardimage1.png',
  '["Quantum", "Research", "Physics", "Computing"]'::jsonb,
  '["Quantum Computing", "Research", "Physics"]'::jsonb,
  'medium',
  30,
  5,
  'Quantum Physicists, Mathematicians, Software Engineers, Research Scientists, PhD Students',
  'Quantum Programming (Qiskit, Cirq), Python, Linear Algebra Libraries, Cloud Quantum Access',
  'Access to quantum computers (IBM Q, Google), High-performance computing cluster, Research workstations',
  500000.00,
  50000.00,
  false,
  NOW(),
  NOW()
);

-- Update focal person information (you can update these with actual member IDs later)
-- COMMENT ON TABLE public.projects IS 'Projects require focal_person_id to be set to a valid member UUID';

COMMENT ON TABLE public.projects IS 'Enhanced projects table with comprehensive metadata for tracking objectives, deliverables, resources, and priorities';
