# Generated by Django 5.0.7 on 2026-01-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_approval_status_user_approved_by_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentee',
            field=models.BooleanField(default=False, help_text='User is registered as a mentee'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='User is registered as a mentor'),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_approved_at',
            field=models.DateTimeField(blank=True, help_text='When mentor application was approved', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('mentee', 'Mentee'), ('mentor', 'Mentor'), ('mentor_mentee', 'Mentor & Mentee')], default='user', max_length=20),
        ),
    ]
