# Generated by Django 5.0.7 on 2026-01-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_mentee_user_is_mentor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="True when user was created with default password and must change it",
            ),
        ),
    ]
