# Generated by Django 5.0.7 on 2026-01-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mentorship Booking',
                'verbose_name_plural': 'Mentorship Bookings',
                'db_table': 'mentorship_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MentorProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'db_table': 'mentors',
                'managed': False,
            },
        ),
    ]
